[program:ai-training-main]
directory=/var/www/html/Ai-training-platform-main/ai_training_platform/
command=/var/www/html/Ai-training-platform-main/ai_training_platform/venv/bin/gunicorn --workers 3 --bind unix:/var/www/html/Ai-training-platform-main/ai_training_platform/app.sock ai_training_platform.wsgi:application
autostart=true
autorestart=true
environment=PYTHONPATH="/var/www/html/Ai-training-platform-main/ai_training_platform"
stderr_logfile=/var/log/ai-training-main.err.log
stdout_logfile=/var/log/ai-training-main.out.log

[group:ai-training-main_group]
programs=ai-training-main